### PR TITLE
Fix Iterating over Nested IDictionary objects

### LINKED ISSUE #320: Iterating over Nested Dictionary in For Loop
It is not possible to loop over the elements of a nested dictionary using a for loop.

For example, this does not work:
```
var dictionary = new Dictionary<string, object> {{
    "People", new Dictionary<string, object> {
        { "ID1", "Jane" },
        { "ID2", "Mike" }
    }
}};

// This currently outputs empty string "" instead of "JaneMike"
Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.Value }}{%endfor%}", Hash.FromDictionary(dictionary));
```

The issue appears to have been caused by the PR for #157.

In my example above, we have a dictionary containing a dictionary containing string values - 2 levels of dictionary.

In #157, there is a dictionary containing a dictionary containing a dictionary containing string values - 3 levels of dictionary.

The PR for #157 added code that intercepts values where the 2nd level is a dictionary, but then only outputs values when the 3rd level is also a dictionary. When the 3rd level is not a dictionary, as in my example where it is a string, it doesn't set anything in the context (since value is Hash is false in BuildContext).

It is possible that nested dictionaries were not supported properly at the time of #157, but simply removing the code added for #157 now resolves all these issues.

There is also the issue that #157 had a bug in it's test case:
```
Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.First }}{%endfor%}", Hash.FromDictionary(dictionary));
```

This test case just ignores the 2nd level entirely and dots into the 3rd level. You wouldn't expect that when iterating over the 2nd level dictionary.

Instead, the test for #157 should have been:
```
Helper.AssertTemplateResult("JaneMike", "{% for item in People %}{{ item.Value.First }}{%endfor%}", Hash.FromDictionary(dictionary));
```

Here you are explicitly stepping through the 2nd level. It is possible that #157 was never an issue and the original writer was just unaware of .Value or perhaps .Value was not supported at that time.

I have submitted a PR which fixes this issue. It also adds 2 new tests and updates the third. 

One new test is for my example, the 2nd level dictionary. 
The other new test shows how you can substitute a list for the dictionary at the 2nd level to keep the direct item.First access desired in #157.
The updated test fixes the original test for #157 to step through the 2nd level dictionary using .Value.

### LINKED ISSUE #414: how do I  loop  the Dictionary<string, object>
### Dotliquid version
2.0.366
### Expected behavior
image
please help me ,how can I loop the Data
### Steps to reproduce the Problem (you can add files)

### LINKED ISSUE #442: Duplicate item rendering of nested IDictionary objects
### Dotliquid version
2.1.469

### Expected behavior
Nested for loops should be possible for nested dictionary data

### Actual behavior
A duplicate entry is rendered for the nested dictionary, in the example below "Mike Doe (ID2)" is rendered twice for a single entry in the dictionary.
```
  Expected: "... Green (ID1), Mike Doe (ID2), \r\nMaths 2: Eric Schmidt (ID3..."
  But was:  "... Green (ID1), Mike Doe (ID2), Mike Doe (ID2), \r\nMaths 2: E..."
```

This appears to be due to `hashValue["itemName"] = key;` in For.BuildContext(), I can't find a reference to "itemName" in the Liquid documents, so a simple fix could be to remove this code - unless it is a known/used feature.

### Steps to reproduce the Problem (you can add files)
```
        [Test]
        public void TestNestedDictionaries()
        {
            var classes = new Dictionary<string, object> {{
                    "Classes", new Dictionary<string, object> {
                        { "C1", new Dictionary<string, object>{
                            { "Name", "English" },
                            { "Level", "1" },
                            { "Students", new Dictionary<string, object> {
                                { "ID1", new Dictionary<string, object>{ { "First", "Jane" }, { "Last", "Green" } } },
                                { "ID2", new Dictionary<string, object>{ { "First", "Mike" }, { "Last", "Doe" } } } } }
                            }
                        },
                        { "C2", new Dictionary<string, object>{
                            { "Name", "Maths" },
                            { "Level", "2" },
                            { "Students", new Dictionary<string, object> {
                                { "ID3", new Dictionary<string, object>{ { "First", "Eric" }, { "Last", "Schmidt" } } },
                                { "ID4", new Dictionary<string, object>{ { "First", "Bruce" }, { "Last", "Banner" } } } } }
                            }
                        }
                    }
            }};

            // Check for loops
            Helper.AssertTemplateResult(expected: @"English 1: Jane Green (ID1), Mike Doe (ID2), 
Maths 2: Eric Schmidt (ID3), Bruce Banner (ID4), 
",
                template: @"{% for class in Classes %}{{class.Name}} {{class.Level}}: {% for student in class.Students %}{{ student.First }} {{ student.Last }} ({{ student.itemName }}), {%endfor%}
{%endfor%}",
                localVariables: Hash.FromDictionary(classes));
        }
```

### PR DESCRIPTION
**Pull request by robin-parker**
- Added test case for multiple nested dictionary traversal in for loops.
- Removed `For.BuildContext` which is replaced by handling for nested KeyValuePair objects in Context.
- The undocumented `item.itemName` for loop property is now an alias of `KeyValuePair.Key`, and is only available when syntax is below 2.2 (resolves #442).
- Implicit access to nested dictionary values removed for syntax 2.2 and above. (resolves #320).

__Wiki updates to follow__
- [DotLiquid for Designers](https://github.com/dotliquid/dotliquid/wiki/DotLiquid-for-Designers) update on how to iterate nested for loops (resolves #414)

### CODE REVIEW

**Comment by microalps** [comment]
See #321 for discussion about whether we should even have this BuildContext method. It seems non-standard entirely.

**Comment by robin-parker** [comment]
> See #321 for discussion about whether we should even have this BuildContext method. It seems non-standard entirely.

Interesting, I didn't notice that there was another ticket related to the same area. I've made a change to this PR to remove BuildContext whilst retaining backwards compatibility.

**Comment by robin-parker** [comment]
@microalps - please could you review - this fixes #442 which is impacting me, and should also fix #320.

**Comment by microalps** [comment]
I'm not convinced about the approach. I get we are trying to avoid a breaking change but we are creating a mess. In your C1 and C2 example, if I call .Name which name should be returned? Also, the right way will not return null when it is expected on Name (only c1 and c2 are valid)  I think we break this one case as it is invalid by all definitions of the word and make a notation in the readme. If @daviburg insists we create a 22a flag. But doing both is middle of the road - where you get run over!!

**Comment by daviburg** [comment]
Help me understand the before and after, what is the current middle of the road which may look like a regression, what is the desired clean but more regression-like change?

**Comment by robin-parker** [comment]
> Help me understand the before and after, what is the current middle of the road which may look like a regression, what is the desired clean but more regression-like change?
> That's the `item.itemName` was working but now no longer will?

@daviburg, the before is demonstrated in this [test case](https://github.com/dotliquid/dotliquid/blob/e18c34c619d946b9669da715fc5621dda7294c6d/src/DotLiquid.Tests/Tags/StandardTagTests.cs#L80-L93).
The `for` tag condenses a KeyValuePair where the Value is Dictionary, by moving the original Key to an entry in the nested dictionary with a new Key of `itemName` - [see here](https://github.com/dotliquid/dotliquid/blob/e18c34c619d946b9669da715fc5621dda7294c6d/src/DotLiquid/Tags/For.cs#L231). 
Unfortunately when iterating the nested dictionary that results in an extra loop (original values + itemName).

The after is to remove the `itemName` entry, and replace it with a `.Key` accessor, which fixes the issue reported in #442 - _this is potentially a breaking change, but I cannot find `itemName` documented anywhere in docs or tests_.
I have also addressed the issue raised in #320, by allowing nested dictionary values to be referenced with or without the `Value` qualifier, see [new test case in this PR](https://github.com/robin-parker/dotliquid/blob/5eb9d3e60410d9794083265d8bf022c428c0b057/src/DotLiquid.Tests/Tags/StandardTagTests.cs#L618-L621).

**Comment by microalps** [comment]
> I have also addressed the issue raised in #320, by allowing nested dictionary values to be referenced with or without the Value qualifier, see new test case in this PR.

This can what I object to. If I am expecting to use .Key and .Value - why is .Prop not returning null and instead returning .Value.Prop ? Or the opposite if someone had programmed up skipping .Value and checks for .Key they will suddenly get a non null response. Middle of the road.

This is an issue which is clearly wrong in C# (and Ruby?) And just needs to be treated like the bug it is. It's not a non-standard behavior, but completely wrong. Like having a Capitalize filter that lower cases - the bug fix would be breaking but absolutely expected.

**Comment by microalps** [comment]
To add some Ruby facts:
Source: https://stackoverflow.com/questions/8206869/iterate-over-hashes-in-liquid-templates
Test: https://replit.com/@microalps/JsonLiquidTemplate#main.rb

Bottom line - skipping key/value level is not valid for sure and returns blank. C# syntax makes sense to use .Key and .Value - but Ruby uses [0] for key and [1] for value.

**Comment by robin-parker** [comment]
@microalps - so you're OK with everything except `item.Prop` being retained as an alias for `item.Value.Prop`, is that a fair summary?

I've put the code for backwards compatibility in Context behind a switch, so the PR strictly applies either the documented Liquid syntax (`item[0]` / `item[1]`) or C# syntax (`item.Key` / `item.Value`) from DotLiquid2.2 onwards.

Is that OK, or should I bump the version again to DotLiquid23?

**Comment by microalps** [comment]
> @microalps - so you're OK with everything
In concept yes. In code, not really. I posted my counter proposal in gitter. See https://github.com/microalps/dotliquid/commit/3e15d7ca9650ffd2ec88827c76df903f4f2f0448

> Is that OK, or should I bump the version again to DotLiquid23?
DotLiquid 22a (221) would probably be safest as it isn't a major change. Was going to do 21a until we added parser versioning as well.

File: src/DotLiquid/Context.cs [hunk 1]
```diff
@@ -522,67 +522,50 @@ private bool TryGetVariable(IEnumerator<string> partsEnumerator, out object vari
...
+                        @object = Liquidize(castCollection.LastOrDefault());
                     }
                 }
+                // No key was present with the desired value and it wasn't one of the directly supported
+                // keywords either. The only thing we got left is to return nil
+                else
+                {
+                    variable = null;
+                    return false;
+                }
```
Comment (microalps) [inline src/DotLiquid/Context.cs:568]: Not sure what this code change has to do with the this PR, please revert or explain

File: src/DotLiquid/Context.cs [hunk 2]
```diff
@@ -697,6 +680,12 @@ private static object Liquidize(object obj)
 
         private static bool IsKeyValuePair(object obj)
         {
+            return TryGetKeyValuePair(obj, out var key, out var value);
```
Comment (microalps) [inline src/DotLiquid/Context.cs:683]: ```out _``` might be better ? Or just rewrite the only other reference to this function and remove it entirely?

File: src/DotLiquid/Context.cs [hunk 3]
```diff
@@ -709,6 +698,8 @@ private static bool IsKeyValuePair(object obj)
                     Type baseType = valueType.GetGenericTypeDefinition();
                     if (baseType == typeof(KeyValuePair<,>))
                     {
+                        key = valueType.GetRuntimeProperty("Key").GetValue(obj);
+                        value = valueType.GetRuntimeProperty("Value").GetValue(obj);
```
Comment (microalps) [inline src/DotLiquid/Context.cs:702]: As mentioned, I don't see any gain by assigning both by reflection when we need 1 or even none for that execution block. Will get back with actual perf comparisons

File: src/DotLiquid/Tags/For.cs [hunk 4]
```diff
@@ -223,18 +221,43 @@ private static List<object> SliceCollectionUsingEach(Context context, IEnumerabl
...
+
+    /// <summary>
+    /// internal class to encapsulate pre DotLiquid 2.2 compatibility in for loop.
+    /// </summary>
+    /// <remarks>
+    /// DotLiquid 2.2 compatibility includes:
+    /// * An undocumented property `itemName` which is an implicit alias for KeyValuePair.Key
+    /// * Implicit access of properties within a nested IDictionary Value
+    /// </remarks>
+    class LegacyKeyValueDrop : Drop
```
Comment (microalps) [inline src/DotLiquid/Tags/For.cs:234]: should this be marked internal?

**Review by microalps — CHANGES_REQUESTED** [review]

File: src/DotLiquid/Tags/For.cs (hunk 4 above)
Comment (robin-parker) [reply src/DotLiquid/Tags/For.cs]: Isn't internal the default visibility for a class?

File: src/DotLiquid/Context.cs (hunk 2 above)
Comment (robin-parker) [reply src/DotLiquid/Context.cs]: Thanks, I haven't seen the discard feature before.

File: src/DotLiquid/Context.cs (hunk 1 above)
Comment (robin-parker) [reply src/DotLiquid/Context.cs]: These changes were made for pre 2.2 combability before implementing the LegacyKeyValueDrop.
I retained them because they:
- update misleading comments to reflect the current code behavior (several comments appeared to be cut/pasted in error).
- merged if statements originally on l535 and l547 into a single block to remove extra `is KeyValuePair`.
- remove a redundant else block (l543).
- remove unreachable branch (l572) caused by the if statement (l562 ensure values can only be size/first/last).
- remove unused variable assigns (l530, 538, 569, 574)

File: src/DotLiquid/Tags/For.cs (hunk 4 above)
Comment (daviburg) [reply src/DotLiquid/Tags/For.cs]: Better make it explicit that leave the reader to guess.

File: src/DotLiquid.Tests/Tags/StandardTagTests.cs [hunk 5]
```diff
@@ -88,10 +88,36 @@ public void TestForWithNestedDictionary()
...
+                expected: "ID1:Jane Green,ID2:Mike Doe,",
+                template: "{% for item in People %}{{ item.itemName }}:{{ item.First }} {{ item.Value.Last }},{%endfor%}",
+                localVariables: Hash.FromDictionary(dictionary),
+                syntax: SyntaxCompatibility.DotLiquid20);
         }
 
+        [Test]
+        public void TestForWithNestedDictionary_DotLiquid22()
+        {
+            var dictionary = new Dictionary<string, object> { {
```
Comment (daviburg) [inline src/DotLiquid.Tests/Tags/StandardTagTests.cs:104]: nit: alignment of the dictionary initializer doesn't look right

File: src/DotLiquid.Tests/Tags/StandardTagTests.cs [hunk 6]
```diff
@@ -591,6 +617,49 @@ public void TestForReversed()
...
+                            }
+                        }
+                    }
+            }};
+
+            // Check for-loops, verify that:
+            // - item.Key OR item[0] --> access the Key
+            // - item.Value.property OR item[1].property --> access values of a nested Hash/IDictionary
+            // - Pre 2.2 syntax (item.property> OR item.itemName) is ignored 
+            Helper.AssertTemplateResult(expected: @"English 1: Jane Green (ID1), Mike Doe (ID2),
```
Comment (daviburg) [inline src/DotLiquid.Tests/Tags/StandardTagTests.cs:648]:
```suggestion
            Helper.AssertTemplateResult(
                expected: @"English 1: Jane Green (ID1), Mike Doe (ID2), 
```

File: src/DotLiquid.Tests/Tags/StandardTagTests.cs [hunk 7]
```diff
@@ -591,6 +617,49 @@ public void TestForReversed()
...
+            Helper.AssertTemplateResult(expected: @"English 1: Jane Green (ID1), Mike Doe (ID2), 
+Maths 2: Eric Schmidt (ID3), Bruce Banner (ID4), 
+",
+                template: @"{% for class in Classes %}{{class.Name}}{{class.Value.Name}} {{class.Value.Level}}: {% for student in class.Value.Students %}{{ student[1].First }} {{ student[1].Last }} ({{ student[0] }}), {%endfor%}
+{%endfor%}",
+                localVariables: Hash.FromDictionary(classes),
+                syntax: SyntaxCompatibility.DotLiquid22);
+
+            // Check dot notation
+            Helper.AssertTemplateResult(expected: "Eric Schmidt",
```
Comment (daviburg) [inline src/DotLiquid.Tests/Tags/StandardTagTests.cs:657]:
```suggestion
            Helper.AssertTemplateResult(
                expected: "Eric Schmidt",

```

File: src/DotLiquid/Context.cs (hunk 1 above)
Comment (microalps) [reply src/DotLiquid/Context.cs]: I reviewed in a compare tool. Much easier to understand. Marking resolved

Comment (microalps) [reply src/DotLiquid/Context.cs]: I reviewed in a compare tool. Much easier to understand. Marking resolved

Comment (microalps) [reply src/DotLiquid/Context.cs]: I reviewed in a compare tool. Much easier to understand. Marking resolved

File: src/DotLiquid/Context.cs (hunk 3 above)
Comment (daviburg) [reply src/DotLiquid/Context.cs:697]: @microalps this is the last issue with this PR, right?
@robin-parker would it be possible to have more specialized helpers to avoid any performance impact from running reflection which may not be required by the caller?

Comment (robin-parker) [reply src/DotLiquid/Context.cs]: I've reverted to `IsKeyValuePair` and added a new helper method `ObjectExtensionMethods.GetPropertyValue` to extract the Key/Values by reflection when needed.

File: src/DotLiquid/Util/ObjectExtensionMethods.cs [hunk 8]
```diff
@@ -48,6 +55,25 @@ public static object Send(this object value, string member, object[] parameters
...
+        /// </summary>
+        /// <param name="object">an object to be interrogated</param>
+        /// <param name="propertyName">the name of the property to get</param>
+        /// <returns>The property value if it exists, otherwise null</returns>
+        public static object GetPropertyValue(this object @object, string propertyName)
+        {
+            if (@object is null)
+                return null;
+
+            Type type = @object.GetType();
```
Comment (daviburg) [inline src/DotLiquid/Util/ObjectExtensionMethods.cs:69]:
```suggestion
            var type = @object.GetType();

```

File: src/DotLiquid/Util/ObjectExtensionMethods.cs [hunk 9]
```diff
@@ -48,6 +55,25 @@ public static object Send(this object value, string member, object[] parameters
...
+            PropertyInfo propertyInfo = type.GetRuntimeProperty(propertyName);
```
Comment (daviburg) [inline src/DotLiquid/Util/ObjectExtensionMethods.cs:70]:
```suggestion
            var propertyInfo = type.GetRuntimeProperty(propertyName);

```

File: src/DotLiquid/Util/ObjectExtensionMethods.cs [hunk 10]
```diff
@@ -48,6 +55,25 @@ public static object Send(this object value, string member, object[] parameters
...
+            if (propertyInfo != null)
+                return propertyInfo.GetValue(@object, null);
```
Comment (daviburg) [inline src/DotLiquid/Util/ObjectExtensionMethods.cs:72]: The whole thing can be replaced  by one-liner without if:
```
                return propertyInfo?.GetValue(@object, null);
```

Comment (daviburg) [reply src/DotLiquid/Util/ObjectExtensionMethods.cs:72]: Actually...
```
                return @object.GetType().GetRuntimeProperty(propertyName)?.GetValue(@object, null);
```

**Review by daviburg — APPROVED** [review]

**Comment by daviburg** [comment]
@microalps see if you can also sign-off this one.

File: src/DotLiquid/Context.cs (hunk 3 above)
Comment (microalps) [reply src/DotLiquid/Context.cs]: Thanks, I can also confirm this PR has no performance change. Signing off.

**Review by microalps — APPROVED** [review]
