### PR TITLE
Math functions on uint and int and other combinations

### LINKED ISSUE #367: Plus filter doesn't work on typeof(uint) but does work on typeof(int)
### Dotliquid version
2.0.314
### Expected behavior
uint should work with the plus operator
### Actual behavior
`Liquid error: Parameter count mismatch.`
### Steps to reproduce the Problem (you can add files)
Pass a drop to a template with a single property of type uint. You should see the above error. Change to an int and it will work.

### PR DESCRIPTION
**Pull request by microalps**
Resolves #367

### CODE REVIEW

File: src/DotLiquid/Util/ExpressionUtility.cs [hunk 1]
```diff
@@ -21,13 +21,13 @@ static ExpressionUtility()
...
-            Add(typeof(Int32), typeof(Int64), typeof(Double), typeof(Decimal), typeof(Single));
-            Add(typeof(UInt32), typeof(Int64), typeof(UInt64), typeof(Double), typeof(Decimal), typeof(Single));
+            Add(typeof(Byte), typeof(UInt16), typeof(Int16), typeof(UInt32), typeof(Int32), typeof(UInt64), typeof(Int64), typeof(Decimal), typeof(Single), typeof(double));
+            Add(typeof(SByte), typeof(Int16), typeof(Int32), typeof(Int64), typeof(Decimal), typeof(Single), typeof(double));
+            Add(typeof(Int16), typeof(Int32), typeof(Int64), typeof(Decimal), typeof(Single), typeof(double));
+            Add(typeof(UInt16), typeof(UInt32), typeof(Int32), typeof(UInt64), typeof(Int64), typeof(Decimal), typeof(Single), typeof(double));
+            Add(typeof(Char), typeof(UInt16), typeof(UInt32), typeof(Int32), typeof(UInt64), typeof(Int64), typeof(Decimal), typeof(Single), typeof(double));
+            Add(typeof(Int32), typeof(Int64), typeof(Decimal), typeof(Single), typeof(double));
+            Add(typeof(UInt32), typeof(Int64), typeof(UInt64), typeof(Decimal), typeof(Single), typeof(double));
```
Comment (microalps) [inline src/DotLiquid/Util/ExpressionUtility.cs:30]: Changes to the order are required to ensure a consistent result whether you pass left, right or right, left. We try to use lowest required upgrade, e.g. decimal > single > double

**Review by daviburg — APPROVED** [review]
